# template to automate aws parameters for use with sam
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Serverless API with DynamoDB

Resources:
  SimpleServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./app.py
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Timeout: 3
      Role:
        Fn::GetAtt:
          - ViewCounterFunctionRole
          - Arn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref MyTable

  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: counter
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH # partition key
